version: "3.4"
networks:
  uzhmp_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.6.0/24
          gateway: 172.1.6.1

services:
  apidocs:
    build:
      context: ./api-docs
      dockerfile: Dockerfile
    networks:
      uzhmp_net:
        ipv4_address: 172.1.6.6

  mapping-api:
    build:
      context: ./map-srv
      dockerfile: Dockerfile
    networks:
      uzhmp_net:
        ipv4_address: 172.1.6.5

  image-api:
    build:
      context: ./img-srv
      dockerfile: Dockerfile
    networks:
      uzhmp_net:
        ipv4_address: 172.1.6.4
    
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    networks:
      uzhmp_net:
        ipv4_address: 172.1.6.3
    depends_on:
      - image-api
      - mapping-api

  web-ui:
    build:
      context: ./web-srv
      dockerfile: Dockerfile
    networks:
      uzhmp_net:
        ipv4_address: 172.1.6.2
    depends_on:
      - api-gateway
      - image-api
      - mapping-api
      - apidocs

      